name: Code Review
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: Louis-7/ai-code-review@main
        env:
          ENGINE: 'deepseek'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEEPSEEK_BASE_URL: 'base_url'
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          CHAT_GPT_MODEL: 'deepseek-chat' # or deepseek-reasoner
          PATH_TO_EXCLUDE: action/**/*, package-lock.json, package.json
          MAX_PATCH_PER_FILE: 2000
          MAX_FILE_PER_PR: 20